# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['gui.py'],
    pathex=[],
    binaries=[
        ('venv/Lib/site-packages/pyzbar/libiconv.dll', 'pyzbar'),
        ('venv/Lib/site-packages/pyzbar/libzbar-64.dll', 'pyzbar'),
    ],
    datas=[('config', 'config')],
    hiddenimports=[
        'ttkbootstrap',
        'pypdf',
        'pypdf.constants',
        'PIL',
        'PIL.Image',
        'PIL.ImageGrab',
        'cv2',
        'pyzbar',
        'pyzbar.pyzbar',
        'psutil',
        'pyperclip',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.kdf.pbkdf2',
        'deepseek_client',
        'LeakGuard.email_leak',
        'LeakGuard.pass_leak',
        'LeakGuard.utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='铁密',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
